FROM python:3

RUN apt-get update
RUN apt-get -qq -y install gcc libgflags2.2 libgflags-dev libgflags-dev zlib1g-dev libzstd-dev python3-setuptools python3-wheel python3-pip
RUN pip3 install regex spacy pytest cython
RUN python3 -m spacy download en && python3 -m spacy download en_core_web_sm

VOLUME ["/input", "/databases", "/output", "/log"]

WORKDIR /app

COPY . .

RUN python3 setup.py build_ext --inplace

ENTRYPOINT ["/usr/local/bin/python3"]

CMD ["entity_recognition.py"]