FROM python:3

RUN apt-get update
RUN apt-get -qq -y install gcc libgflags2.2 libgflags-dev libgflags-dev zlib1g-dev libzstd-dev python3-setuptools python3-wheel python3-pip
RUN pip3 install --upgrade pip
RUN pip3 uninstall numpy
RUN pip3 install numpy
RUN pip3 install regex pytest cython

VOLUME ["/input", "/output", "/log"]

WORKDIR /app

COPY . .

RUN python3 setup.py build_ext --inplace
